// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yqudouwsqrdctkfgghen.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlxdWRvdXdzcXJkY3RrZmdnaGVuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzNDM0NzgsImV4cCI6MjA2MDkxOTQ3OH0.5snkHoEo3P9vT4OYKW2GkMbSSk9vNdmogxaHV-fn-os";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);